tasks:
  # downloading task
  download-rss:
    rss: $rssfeed
    # fetch all the feed series
    all_series: yes
    proper_movies: yes
    # use transmission to download the torrents
    transmission:
      host: localhost
      port: 9091
      username: transmission-daemon
      password: $transmissionpass
      addpaused: no
